export class GetTermsOfUseUseCase {
    private language: LanguageEnum
    constructor(language?: string) {
        // super()
        this.language = language ? this.toLanguageEnum(language) : LanguageEnum.ENUS
    }

    public async buildUseCase(): Promise<any>{
        return this.getTermsOfUse(this.language)
    }
    
    private getTermsOfUse = async (requestedLanguage: LanguageEnum): Promise<any> => {
        let goinTerms: GoInTerms[] = [
            {
                title: {
                    'pt-br': 'Termos de Uso',
                    'en-us': 'Terms of Use',
                    'es-es': 'Términos de Uso'
                },
                description: {
                    'pt-br': '[PT-BR] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                    'en-us': '[EN-US] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                    'es-es': '[ES-ES] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                } 

            },
            {
                title: {
                    'pt-pt': 'Política de Meia Entrada',
                    'en-us': 'Half Price Policy',
                    'es-es': 'Policía a Mitad de Precio'
                },
                description: {
                    'pt-br': '[PT-BR] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                    'en-us': '[EN-US] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                    'es-es': '[ES-ES] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                } 

            },
            {
                title: {
                    'pt-br': 'Política de Privacidade',
                    'en-us': 'Privacy Policy',
                    'es-es': 'Política de Privacidad'
                },
                description: {
                    'pt-br': '[PT-BR] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                    'en-us': '[EN-US] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                    'es-es': '[ES-ES] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a aliquet nisl. Sed lorem metus, efficitur eu urna ut, sollicitudin venenatis eros. Integer id odio egestas, pulvinar tortor in, consequat arcu. In felis odio, dapibus sit amet ornare eget, aliquet et felis. In id turpis diam. Vestibulum semper ultrices diam, quis viverra odio posuere eget. Aliquam ac dui sed dolor congue scelerisque. Vestibulum tortor tortor, ultrices a lorem eget, rutrum feugiat justo. Praesent blandit at lacus tincidunt aliquam. Ut finibus enim nec posuere porttitor. Proin eget risus auctor, lobortis dolor pretium, fermentum felis. Quisque vitae justo eu augue aliquet porta sed vitae nisi. Nulla efficitur, augue posuere pretium eleifend, mauris ipsum rhoncus orci, ut finibus leo sem at erat. Pellentesque et purus mattis, iaculis dolor in, lobortis purus. Nunc pellentesque eleifend metus, ac vehicula odio facilisis vel. Donec sit amet pellentesque elit. Vivamus dapibus massa vel erat rutrum, sit amet efficitur felis fermentum. Vivamus ac gravida odio. Quisque cursus ipsum eget velit blandit aliquet. Proin egestas sit amet elit a eleifend. Curabitur sit amet nisi sit amet nulla bibendum tristique. Mauris at placerat odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at quam tortor. Suspendisse at feugiat dolor, sit amet tempor mauris. Quisque blandit hendrerit mollis. Duis sollicitudin tempor elit sed condimentum. Quisque a facilisis metus. Maecenas purus metus, finibus a pulvinar eu, mollis semper ex. Vestibulum sit amet diam accumsan, consectetur massa vitae, tempor ligula. Duis a nisi sed quam ullamcorper sodales. Vestibulum vestibulum justo quis nisl ultricies, eget consectetur risus aliquet. Fusce aliquet sit amet justo nec aliquet. Aliquam finibus nisi elit, ac pharetra elit cursus vitae. Mauris pretium placerat elit a gravida. Quisque in lacus id massa malesuada pharetra. Sed aliquam enim ut massa fringilla, in sagittis diam ultricies. Vestibulum at mollis sem. Nunc in aliquam sapien. Integer iaculis elementum nulla non consequat. Ut ac ante sed massa feugiat pharetra vel a purus. Donec interdum porta leo, eget rutrum ligula dignissim nec. Mauris condimentum ipsum lectus. Integer blandit finibus nulla id suscipit. Integer venenatis augue nec volutpat lacinia. Sed sit amet aliquet dui, et molestie sem. Donec congue erat ut sem aliquam, in rutrum sapien tempor. Maecenas justo justo, varius a laoreet eget, pretium ac augue. Suspendisse potenti. Fusce purus sapien, tristique sit amet felis vehicula, faucibus malesuada turpis. Sed pellentesque tristique accumsan. Maecenas varius a eros ut commodo. Duis fermentum dui arcu, vel tristique augue facilisis et. Proin eget libero eget magna eleifend pulvinar. In nibh mi, ultrices eget arcu a, auctor efficitur tortor.',
                }  
            }
        ]

        let returnableTermsOfUse = goinTerms.map(
            (term) => {
                let language = requestedLanguage
                if (!term.title[language] || !term.description[language]) {
                    language = LanguageEnum.ENUS
                }
                return {
                    title: term.title[language],
                    description: term.description[language]
                }
            }
        )
        return returnableTermsOfUse
    }

    private toLanguageEnum = (language: string): LanguageEnum => {
        if (LanguageEnum[language]) {
            return LanguageEnum[language]   
        }
        // throw new OSError('Please, insert a valid language', 500)
        throw new Error(`${language} is invalid. Please, insert a valid language`)
    }
}

export interface GoInTerms {
    title: { [index: string]: string }
    description: { [index: string]: string }
}

export enum LanguageEnum {
    ENUS = 'en-us', //english of united states
    ENUK = 'en-uk', //english of united kingdom
    PTPT = 'pt-pt', //portuguese of potugal
    PTBR = 'pt-br', //portuguese of brazil
    ESES = 'es-es' // spanish of spain
}


// let getTermsOfUseUseCase = new GetTermsOfUseUseCase('ENUS')
// console.log(getTermsOfUseUseCase.buildUseCase())

// getTermsOfUseUseCase = new GetTermsOfUseUseCase('PTBR')
// console.log(getTermsOfUseUseCase.buildUseCase())

// getTermsOfUseUseCase = new GetTermsOfUseUseCase('ESES')
// console.log(getTermsOfUseUseCase.buildUseCase())

let getTermsOfUseUseCase = new GetTermsOfUseUseCase('PTPT')
console.log(getTermsOfUseUseCase.buildUseCase())

// getTermsOfUseUseCase = new GetTermsOfUseUseCase()
// console.log(getTermsOfUseUseCase.buildUseCase())


